name: PR Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on: [pull_request]

jobs:
  call_workflow:
    name: Run PR Build Workflow
    uses: ballerina-platform/ballerina-standard-library/.github/workflows/pull-request-build-template.yml@main
